### ISSUE TITLE
TheTruthBehindMultipleReturnValues() is failing

### ISSUE THREAD

**Issue by epitka** [ChrisMarinos/FSharpKoans#33] opened 2014-12-03 17:21 UTC
Maybe this is my not understanding how it works but,  shouldn't result be (9, 27). Printout says, Expected ((9, 27)) but was ((9, 27)) 

[<Koan>]
    let TheTruthBehindMultipleReturnValues() =

```
    let squareAndCube x =
        (x ** 2.0, x ** 3.0)

    let result = squareAndCube 3.0

    let tuple = (9, 27)
    let tuple2 = (9, 27)

    AssertEquality tuple tuple2  // this passes

    AssertEquality result tuple // this fails ????
```

**Comment by ChrisMarinos** [comment] 2014-12-03 17:36
Yes, this is a known issue, and it's a duplicate of #15. See my writeup there for more information.

**Closed as completed** 2014-12-03 17:36 UTC
